### ISSUE TITLE
Override body margin

### ISSUE THREAD

**Issue by griffinlacek** [erikanso/prj-rev-bwfs-tea-cozy#1]
On most browsers, body has an automatic margin applied to it (in Chrome's case it's 8px). This means there's always a small black buffer around your page. Not a big deal at all, but something to typically override.

So, we can solve this with this style:

body { margin: 0; }

https://github.com/erikanso/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L1-L7

**Comment by erikanso** [comment]
I noticed that there was something going on with the margin. Thanks!
