### ISSUE TITLE
Left-aligning footer

### ISSUE THREAD

**Issue by griffinlacek** [erikanso/prj-rev-bwfs-tea-cozy#2]
It looks like you tried to left align your footer, but wasn't able to get it working. Flex can be tricky like that when you've got it all over your page and there gets to be a few moving parts. The easiest way to left align the footer is to use the align-self style. This overrides the align-content: center style that you applied to your content class.

So, we can replace the footer styles with this line of code

`align-self: left;`

https://github.com/erikanso/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L147-L156

**Comment by erikanso** [comment]
Good to know! I didn't understand why there was another "align" property and was struggling with this point for a while.
