### ISSUE TITLE
Indentation suggestion

### ISSUE THREAD

**Issue by griffinlacek** [erikanso/prj-rev-bwfs-tea-cozy#4]
Small indentation and code spacing suggestion for you. Consider it and compare my suggestion to yours!

```
<span class="tea">
    <img class="tea-photo"src="resources/images/berry-blitz.jpg" />
    <h4>Fall Berry Blitz Tea</h4>
</span>
```

There's just more space here and it seems more readable to me.

https://github.com/erikanso/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/index.html#L38-L47

**Comment by erikanso** [comment]
This definitely makes sense and is a reminder for me to always review my code one more time before submitting. Thanks!
